apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtdwh-mgmt.fullname" . }}-backend
  labels:
    app: rtdwh-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: rtdwh-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtdwh-mgmt.fullname" . }}-backend
  labels:
    app: rtdwh-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rtdwh-backend
  template:
    metadata:
      labels:
        app: rtdwh-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
