{{- if .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rtdwh-mgmt.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
spec:
  rules:
    - host: {{ .Values.ingress.host | default "rtdwh.local" }}
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "rtdwh-mgmt.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rtdwh-mgmt.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
